aeg-logger:
  transports:
# adding this via API
#    - type: console
#      level: debug
#      colorize: false
#      timestamp: true
    - type: file
      level: debug
      filename: logs/aeg-logger.log
# example
#    - type: paperTrail
#      level: debug
#      host: x
#      port: x
#      program: test
